apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world
  namespace: gaming
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
