apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutty-drive
  namespace: development
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
