apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotfiles
  namespace: {{ .Release.Namespace }}
  labels:
    app: dotfiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotfiles
  template:
    metadata:
      labels:
        app: dotfiles
    spec:
      containers:
      - name: dotfiles
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        {{- range .Values.network.ports }}
        - name: {{ .name }}
          containerPort: {{ .port }}
        {{- end }}
        volumeMounts:
        - name: nutty-drive
          mountPath: /root/Code
          subPath: code
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: nutty-drive
        persistentVolumeClaim:
          claimName: nutty-drive
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: File
