apiVersion: v1
kind: Service
metadata:
  name: terraria-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: terraria
    function: server
  ports:
  {{- range .Values.network.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol }}
  {{- end }}
  externalIPs:
  {{- range .Values.network.externalIPs }}
  - {{ . }}
  {{- end }}
