apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-ftb-world
  namespace: gaming
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
