apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: gaming
spec:
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: server
        image: nutty7t/minecraft-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: minecraft-world-volume
          mountPath: "/minecraft"
      initContainers:
      - name: minecraft-restore
        image: nutty7t/minecraft-restore:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: minecraft-world-volume
          mountPath: "/minecraft"
      volumes:
      - name: minecraft-world-volume
        persistentVolumeClaim:
          claimName: minecraft-world-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: gaming
spec:
  selector:
    app: minecraft
  type: NodePort
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25565
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-world-pvc
  namespace: gaming
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
