apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: 21b02f46@nutty.email
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
