apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: gaming
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/client-max-body-size: "1000M"
spec:
  rules:
  - host: restore.nutty.services
    http:
      paths:
      - backend:
          serviceName: minecraft-restore
          servicePort: 5000
